pull_request_rules:
  - name: Ask to resolve conflict
    conditions:
      - conflict
      - -author=dependabot[bot]
      - or:
          - -draft # Don't report conflicts on regular draft.
          - and: # Do report conflicts on draft that are scheduled for the next major release.
              - draft
              - milestone~=v[0-9]\.[0-9]{2}
    actions:
      comment:
        message: This pull request has merge conflicts. Could you please resolve them
          @{{author}}? ðŸ™

  - name: Approve trivial maintainer PRs
    conditions:
      - base!=stable
      - label=trivial
      - author=@sigp/lighthouse
      - -conflict
    actions:
      review:
        type: APPROVE

  - name: Add ready-to-merge labeled PRs to merge queue
    conditions:
      # All branch protection rules are implicit: https://docs.mergify.com/conditions/#about-branch-protection
      - base!=stable
      - label=ready-for-merge
      - label!=do-not-merge
    actions:
      queue:

queue_rules:
  - name: default
    batch_size: 8
    batch_max_wait_time: 60 s
    checks_timeout: 10800 s
    merge_method: squash
    commit_message_template: |
      {{ title }} (#{{ number }})

        {{ body | get_section("## Issue Addressed", "") }}


        {{ body | get_section("## Proposed Changes", "") }}
    queue_conditions:
      - "#approved-reviews-by >= 1"
      - "check-success=license/cla"
      - "check-success=target-branch-check"
      - "label!=do-not-merge"
    merge_conditions:
      - "check-success=test-suite-success"
      - "check-success=local-testnet-success"
